"use strict";
var mongoose = require("mongoose");
var Promise = require("bluebird");
var Schema = mongoose.Schema;

var schema = new Schema({
	"url": {"type": String, unique : true, required : true},
	"id": Number,
	"html_url": String,
	"diff_url": String,
	"patch_url": String,
	"issue_url": String,
	"number": Number,
	"state": String,
	"locked": Boolean,
	"title": String,
	"user": {
		"login": String,
		"id": Number,
		"avatar_url": String,
		"gravatar_id": String,
		"url": String,
		"html_url": String,
		"followers_url": String,
		"following_url": String,
		"gists_url": String,
		"starred_url": String,
		"subscriptions_url": String,
		"organizations_url": String,
		"repos_url": String,
		"events_url": String,
		"received_events_url": String,
		"site_admin": Boolean
	},
	"body": String,
	"created_at": Date,
	"updated_at": String,
	"closed_at": String,
	"merged_at": String,
	"merge_commit_sha": String,
	"assignee": String,
	"milestone": String,
	"commits_url": String,
	"review_comments_url": String,
	"review_comment_url": String,
	"comments_url": String,
	"statuses_url": String,
	"head": {
		"label": String,
		"ref": String,
		"sha": String,
		"user": {
			"login": String,
			"id": Number,
			"avatar_url": String,
			"gravatar_id": String,
			"url": String,
			"html_url": String,
			"followers_url": String,
			"following_url": String,
			"gists_url": String,
			"starred_url": String,
			"subscriptions_url": String,
			"organizations_url": String,
			"repos_url": String,
			"events_url": String,
			"received_events_url": String,
			"site_admin": Boolean
		},
		"repo": {
			"id": Number,
			"name": String,
			"full_name": String,
			"owner": {
				"login": String,
				"id": Number,
				"avatar_url": String,
				"gravatar_id": String,
				"url": String,
				"html_url": String,
				"followers_url": String,
				"following_url": String,
				"gists_url": String,
				"starred_url": String,
				"subscriptions_url": String,
				"organizations_url": String,
				"repos_url": String,
				"events_url": String,
				"received_events_url": String,
				"site_admin": Boolean
			},
			"private": Boolean,
			"html_url": String,
			"description": String,
			"fork": Boolean,
			"url": String,
			"forks_url": String,
			"keys_url": String,
			"collaborators_url": String,
			"teams_url": String,
			"hooks_url": String,
			"issue_events_url": String,
			"events_url": String,
			"assignees_url": String,
			"branches_url": String,
			"tags_url": String,
			"blobs_url": String,
			"git_tags_url": String,
			"git_refs_url": String,
			"trees_url": String,
			"statuses_url": String,
			"languages_url": String,
			"stargazers_url": String,
			"contributors_url": String,
			"subscribers_url": String,
			"subscription_url": String,
			"commits_url": String,
			"git_commits_url": String,
			"comments_url": String,
			"issue_comment_url": String,
			"contents_url": String,
			"compare_url": String,
			"merges_url": String,
			"archive_url": String,
			"downloads_url": String,
			"issues_url": String,
			"pulls_url": String,
			"milestones_url": String,
			"notifications_url": String,
			"labels_url": String,
			"releases_url": String,
			"created_at": String,
			"updated_at": String,
			"pushed_at": String,
			"git_url": String,
			"ssh_url": String,
			"clone_url": String,
			"svn_url": String,
			"homepage": String,
			"size": Number,
			"stargazers_count": Number,
			"watchers_count": Number,
			"language": String,
			"has_issues": Boolean,
			"has_downloads": Boolean,
			"has_wiki": Boolean,
			"has_pages": Boolean,
			"forks_count": Number,
			"mirror_url": String,
			"open_issues_count": Number,
			"forks": Number,
			"open_issues": Number,
			"watchers": Number,
			"default_branch": String
		}
	},
	"base": {
		"label": String,
		"ref": String,
		"sha": String,
		"user": {
			"login": String,
			"id": Number,
			"avatar_url": String,
			"gravatar_id": String,
			"url": String,
			"html_url": String,
			"followers_url": String,
			"following_url": String,
			"gists_url": String,
			"starred_url": String,
			"subscriptions_url": String,
			"organizations_url": String,
			"repos_url": String,
			"events_url": String,
			"received_events_url": String,
			"site_admin": Boolean
		},
		"repo": {
			"id": Number,
			"name": String,
			"full_name": String,
			"owner": {
				"login": String,
				"id": Number,
				"avatar_url": String,
				"gravatar_id": String,
				"url": String,
				"html_url": String,
				"followers_url": String,
				"following_url": String,
				"gists_url": String,
				"starred_url": String,
				"subscriptions_url": String,
				"organizations_url": String,
				"repos_url": String,
				"events_url": String,
				"received_events_url": String,
				"site_admin": Boolean
			},
			"private": Boolean,
			"html_url": String,
			"description": String,
			"fork": Boolean,
			"url": String,
			"forks_url": String,
			"keys_url": String,
			"collaborators_url": String,
			"teams_url": String,
			"hooks_url": String,
			"issue_events_url": String,
			"events_url": String,
			"assignees_url": String,
			"branches_url": String,
			"tags_url": String,
			"blobs_url": String,
			"git_tags_url": String,
			"git_refs_url": String,
			"trees_url": String,
			"statuses_url": String,
			"languages_url": String,
			"stargazers_url": String,
			"contributors_url": String,
			"subscribers_url": String,
			"subscription_url": String,
			"commits_url": String,
			"git_commits_url": String,
			"comments_url": String,
			"issue_comment_url": String,
			"contents_url": String,
			"compare_url": String,
			"merges_url": String,
			"archive_url": String,
			"downloads_url": String,
			"issues_url": String,
			"pulls_url": String,
			"milestones_url": String,
			"notifications_url": String,
			"labels_url": String,
			"releases_url": String,
			"created_at": String,
			"updated_at": String,
			"pushed_at": String,
			"git_url": String,
			"ssh_url": String,
			"clone_url": String,
			"svn_url": String,
			"homepage": String,
			"size": Number,
			"stargazers_count": Number,
			"watchers_count": Number,
			"language": String,
			"has_issues": Boolean,
			"has_downloads": Boolean,
			"has_wiki": Boolean,
			"has_pages": Boolean,
			"forks_count": Number,
			"mirror_url": String,
			"open_issues_count": Number,
			"forks": Number,
			"open_issues": Number,
			"watchers": Number,
			"default_branch": String
		}
	},
	"_links": {
		"self": {
			"href": String
		},
		"html": {
			"href": String
		},
		"issue": {
			"href": String
		},
		"comments": {
			"href": String
		},
		"review_comments": {
			"href": String
		},
		"review_comment": {
			"href": String
		},
		"commits": {
			"href": String
		},
		"statuses": {
			"href": String
		}
	},
	"merged": Boolean,
	"mergeable": Boolean,
	"mergeable_state": String,
	"merged_by": String,
	"comments": Number,
	"review_comments": Number,
	"commits": Number,
	"additions": Number,
	"deletions": Number,
	"changed_files": Number
});

var PullRequest = mongoose.model("PullRequest", schema);

Promise.promisifyAll(PullRequest);
Promise.promisifyAll(PullRequest.prototype);

module.exports = PullRequest;
